[env] format bash script
Signed-off-by: trantor <postrantor@gmail.com>

diff --git a/quadruped/.env/robot b/quadruped/.env/robot
--- a/quadruped/.env/robot
+++ b/quadruped/.env/robot
@@ -9,14 +9,14 @@ fi
 
 # rmw
 export RMW_IMPLEMENTATION=rmw_cyclonedds_cpp
-# export CYCLONEDDS_URI=
+# export CYCLONEDDS_URI=""
 
 # gazebo
 architecture=$(uname -m)
 if [[ "$architecture" == "x86_64" ]]; then
     source /usr/share/gazebo/setup.sh
-    #export GZ_VERSION=fortress
     export GAZEBO_PLUGIN_PATH=$GAZEBO_PLUGIN_PATH:/opt/ros/${ROS_DISTRO}/lib
+    #export GZ_VERSION=fortress
     # "/usr/lib/x86_64-linux-gnu/gazebo-11/plugins:/opt/ros/${ROS_DISTRO}/opt/rviz_ogre_vendor/lib:/opt/rti.com/rti_connext_dds-6.0.1/lib/x64Linux4gcc7.3.0:/opt/rti.com/rti_connext_dds-6.0.1/bin:/opt/ros/${ROS_DISTRO}/lib/x86_64-linux-gnu:/usr/share/gurumdds/cmake/../../../lib:/opt/ros/${ROS_DISTRO}/lib:/usr/lib/x86_64-linux-gnu/gazebo-11/plugins::/usr/lib/x86_64-linux-gnu/gazebo-11/plugins:/usr/lib/x86_64-linux-gnu/gazebo-11/plugins:"
 elif [[ "$architecture" == "aarch64" ]]; then
     echo "Current machine is ARM architecture"
@@ -24,50 +24,45 @@ else
     echo "Unknown CPU Architecture: $architecture"
 fi
 
-# ros2
-function install-dependencies() {
-    # sudo rosdep init
-    # rosdep update
-    rosdep install \
-        -y \
-        --from-paths "$@" \
-        --ignore-src \
-        --skip-keys "serial \
-                unitree_msgs \
-                unitree_sdk \
-                quadruped \
-                tinynurbs \
-                tiny_ekf \
-                quadprog \
-                matplotlib_cpp \
-                qpOASES \
-                SuiteSparse \
-                message_generation \
-                message_runtime \
-                catkin \
-                xpp_msgs"
-}
+# add colcon
+source ${QUAD_WORKDIR}/.env/colcon_cd.sh
+source ${QUAD_WORKDIR}/.env/colcon-argcomplete.bash
+export _colcon_cd_root=/opt/ros/${ROS_DISTRO}/
 
-# colcon build
-function colcon_ws() {
+# set colcon::build
+export COLCON_DEFAULTS_FILE=${QUAD_WORKDIR}/.config/build-args.yaml # for `colcon build`
+export COLCON_HOME=${QUAD_WORKDIR}/.config/                         # for colcon.meta
+
+# add vcs-complete
+source ${QUAD_WORKDIR}/.env/vcs.bash
+export QUAD_REPO=${QUAD_WORKDIR}/.config/quadruped.repos
+
+# go to workspace
+function cd_ws() {
     declare -A paths=(
-        ["model"]="/project/model_ws"
-        ["control"]="/project/control_ws"
-        ["demo"]="/project/demo_ws"
-        ["unitree"]="/project/unitree_ws"
-        ["gazebo"]="/project/gazebo_ws"
-        ["sim"]="/project/sim_ws"
+        ["model"]="${QUAD_WORKDIR}"
+        ["control"]="${HOME}/project/control_ws"
+        ["unitree"]="${HOME}/project/unitree_ws"
     )
 
     if [[ -z ${paths[$1]} ]]; then
-        echo "Invalid argument. Usage: colcon_ws [control|demo|unitree] [custom_args]"
+        echo "Invalid argument. Usage: cd workspace [control|demo|unitree] [custom_args]"
         return 1
     fi
 
-    cd ${HOME}/"${paths[$1]}"
-    shift
-    #[parallel work](https://colcon.readthedocs.io/en/released/reference/executor-arguments.html)
-    #[make/colcon thread number](https://robotics.stackexchange.com/questions/97896/colcon-build-number-of-threads)
+    cd "${paths[$1]}"
+
+    if [ -n "$BASH_VERSION" ]; then
+        source "./install/setup.bash"
+    elif [ -n "$ZSH_VERSION" ]; then
+        source "./install/setup.zsh"
+    fi
+}
+
+# colcon build target workspace
+function colcon_ws() {
+    cd_ws $1
+    shift # drop before args
     colcon build "$@"
 }
 
@@ -99,42 +94,82 @@ function colcon_remove() {
     done
 }
 
-# workspace
-function cd_ws() {
-    declare -A paths=(
-        ["model"]="/project/model_ws"
-        ["control"]="/project/control_ws"
-        ["demo"]="/project/demo_ws"
-        ["unitree"]="/project/unitree_ws"
-        ["gazebo"]="/project/gazebo_ws"
-        ["sim"]="/project/sim_ws"
-    )
-
-    if [[ -z ${paths[$1]} ]]; then
-        echo "Invalid argument. Usage: cd workspace [control|demo|unitree] [custom_args]"
-        return 1
-    fi
-
-    cd ${HOME}/"${paths[$1]}"
-
-    if [ -n "$BASH_VERSION" ]; then
-        source ${HOME}/"${paths[$1]}"/install/setup.bash
-    elif [ -n "$ZSH_VERSION" ]; then
-        source ${HOME}/"${paths[$1]}"/install/setup.zsh
-    fi
+# import quad repo
+function import-quad-src() {
+  echo "importing quad src..."
+  # 创建 src 目录，存在时不报错
+  if ! mkdir -p ./src; then
+    echo "Error: Failed to create ./src directory." >&2
+    return 1
+  fi
+  # 导入仓库
+  if ! vcs import --retry 3 --force -w 5 --input "$QUAD_REPO" ./src; then
+    echo "Error: Failed to import repositories using vcs." >&2
+    return 1
+  fi
+  echo "Import completed successfully."
+  return 0
 }
 
-alias catkin_dev='sudo chmod a+rw /dev/i2c-1'
+# install dependencies from packages.xml
+function install-dependencies() {
+    # sudo rosdep init
+    # rosdep update
+    rosdep install \
+        -y \
+        --from-paths "$@" \
+        --ignore-src \
+        --skip-keys "serial \
+                unitree_msgs \
+                unitree_sdk \
+                quadruped \
+                tinynurbs \
+                tiny_ekf \
+                quadprog \
+                matplotlib_cpp \
+                qpOASES \
+                SuiteSparse \
+                message_generation \
+                message_runtime \
+                catkin \
+                xpp_msgs"
+}
 
-# add colcon
-source ${QUAD_WORKDIR}/.env/colcon_cd.sh
-source ${QUAD_WORKDIR}/.env/colcon-argcomplete.bash
-export _colcon_cd_root=/opt/ros/${ROS_DISTRO}/
+# 忽略指定目录的函数
+function ignore-directory() {
+  local ignore_file="./src/.colcon-ignore-$1"
+  local path_pattern="*/$2"
 
-# set colcon::build
-export COLCON_DEFAULTS_FILE=${QUAD_WORKDIR}/.config/build-args.yaml # for `colcon build`
-export COLCON_HOME=${QUAD_WORKDIR}/.config/                         # for colcon.meta
+  if [[ ! -e $ignore_file ]]; then
+    touch "$ignore_file"
+    echo -e "\033[1;31mYou should \`touch ./src/$2/COLCON_IGNORE\`\033[0m"
 
-# add vcs-complete
-source ${QUAD_WORKDIR}/.env/vcs.bash
-export QUAD_REPO=${QUAD_WORKDIR}/.config/quadruped.repos
+    for dir in $(find ./ -type d -maxdepth 3 -path "$path_pattern" 2>/dev/null); do
+      if [[ -d "$dir" ]]; then
+        if ! touch "$dir/COLCON_IGNORE"; then
+          echo -e "\033[1;31mWarning: Failed to create COLCON_IGNORE in $dir.\033[0m" >&2
+        else
+          echo "Created COLCON_IGNORE in $dir"
+        fi
+      fi
+    done
+  fi
+}
+
+# 需要忽略的目录列表
+function ignore-colcon-pkg() {
+  declare -A IGNORE_LIST=(
+    [control]="ros2-control/ros2-control"
+    [controllers]="ros2-control/ros2-controllers"
+    [parameter]="ros2-control/generate-parameter-library"
+    [infrastructure]="ros2-infrastructure"
+    [reference]="reference"
+    [interfaces]="interfaces/geometry2"
+    [simulation]="simulation"
+  )
+
+  # 遍历忽略目录
+  for key in "${!IGNORE_LIST[@]}"; do
+    ignore-directory "$key" "${IGNORE_LIST[$key]}"
+  done
+}
